import "@/app/globals.css";
import NavContainer from "@/components/NavContainer";
import Header from "@/components/Header";

export const metadata = {
  title: "Ekkremis",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
        <div className="flex">
          <NavContainer />
          <div className="w-screen md:ml-64 ml-16">
            <Header />
            {children}
          </div>
        </div>
  );
}


