import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Header from "../components/Header";

const poppins = Poppins({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ["latin"]
});

export const metadata = {
  title: "Ekkremis",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased`}
      >
        <div className="flex">
          <Navbar />
          <div className="w-screen">
            <Header />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
